name : Slack Notification
on :
  workflow_call:
    inputs:
      color:
        required: true
        type: string
      msg:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
jobs :
  SlackNotification :
    name : Slack Notification
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v2
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_COLOR : ${{ inputs.color }}
          SLACK_USERNAME : git-actions-test
          SLACK_MESSAGE : ${{ inputs.msg }}
          SLACK_LINK_NAMES : true
          SLACK_FOOTER : 'github action build'
          SLACK_WEBHOOK : ${{ secrets.SLACK_WEBHOOK_URL }}
